GET http://localhost:8888

###
GET http://localhost:8888/dbsnbsid

###
POST http://localhost:8888/student/register
content-type: application/json ;

{
    "name":"chinu",
    "roll":123
}

###
GET  http://localhost:8888/student/student-details
